language: common-lisp
sudo: required

os:
  - linux

before_install:
  - sudo apt-get update
  - sudo apt-get install sbcl -y
  - curl -O https://beta.quicklisp.org/quicklisp.lisp
  - sbcl --load install.lisp --non-interactive
  - git clone https://github.com/asdf-vm/asdf.git lisp/asdf

install:
  - echo "(push (concatenate 'string (sb-posix:getcwd) \"/\") asdf:*central-registry*)" >> $HOME/.sbclrc
  - sbcl --non-interactive --eval '(ql:quickload "wamp")' 
  
