language: common-lisp
sudo: required

os:
  - linux

before_install:
  - sudo apt-get update
  - sudo apt-get install sbcl -y
  - curl -O https://beta.quicklisp.org/quicklisp.lisp
  - sbcl --load install.lisp --eval "(exit)"
  
  
