language: common-lisp
sudo: required
cache:
  directories:
    - $HOME/quicklisp
    - $HOME/.cache/common-lisp
  
os:
  - linux

before_install:
  - sudo apt-get update
  - sudo apt-get install sbcl -y
  - curl -o $HOME/quicklisp.lisp https://beta.quicklisp.org/quicklisp.lisp
  - sbcl --load install.lisp --non-interactive
  - git clone https://github.com/fare/asdf.git $HOME/common-lisp/asdf
  - echo | sbcl --version

install:
  # Add the current working directory to the asdf repository list
  - echo "(push (concatenate 'string (sb-posix:getcwd) \"/\") asdf:*central-registry*)" >> $HOME/.sbclrc
  # Install dependencies
  - sbcl --non-interactive --eval '(ql:quickload "wamp")'
  - sbcl --non-interactive --eval '(ql:quickload "wamp/test")'

jobs: 
  include:
    - stage: test
      name: "Unit"
      script: sbcl --non-interactive --eval '(asdf:test-system "wamp")' | exit 1
      language: lisp
