version: 2
jobs:
  build:
    docker:
      - image: mmgeorge/sbcl:latest
    steps:
      - checkout:
          path: ~/common-lisp/wamp
      - run:
          name: Update
          command: cd ~/common-lisp/cl-expect && git pull
      - run:
          name: Run cl-expect
          command: cd ~/common-lisp/cl-wamp && sbcl --load run.lisp --non-interactive
      - store_test_results:
          path: ~/common-lisp/cl-wamp/.test-output
    
