version: 2
jobs:
  build:
    docker:
      - image: mmgeorge/sbcl:latest
    steps:
      - checkout:
          path: ~/common-lisp/wamp
      - run:
          name: Run cl-expect
          command: sbcl --load run.lisp --non-interactive
    
