version: 2
jobs:
  build:
    docker:
      - image: mmgeorge/sbcl:latest
    steps:
      - checkout
      - run: mv $CIRCLE_WORKING_DIRECTORY $HOME/common-lisp/
      - run:
          name: Run cl-expect
          command: sbcl --load run.lisp --non-interactive
    
